export const CHECK_LOCAL_STORAGE = 'CHECK_LOCAL_STORAGE';
export const CHECK_LOCAL_STORAGE_SUCCESS = 'CHECK_LOCAL_STORAGE_SUCCESS';
export const CHECK_LOCAL_STORAGE_FAILED = 'CHECK_LOCAL_STORAGE_FAILED';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_USER_INFO_PENDING = 'GET_USER_INFO_PENDING';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const SET_USER_INFO_PENDING = 'SET_USER_INFO_PENDING';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAILED = 'SET_USER_INFO_FAILED';

export const GET_USER_TRANSACTIONS_PENDING = 'GET_USER_TRANSACTIONS_PENDING';
export const GET_USER_TRANSACTIONS_SUCCESS = 'GET_USER_TRANSACTIONS_SUCCESS';
export const GET_USER_TRANSACTIONS_FAILED = 'GET_USER_TRANSACTIONS_FAILED';

export const SELECT_PLAN = 'SELECT_PLAN';

export const SUBMIT_ORDER = 'SUBMIT_ORDER';
